version: '3'
services:
  django:
    image: djangoalpine
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - 8000:8000
    networks:
      - testnet
  ubuntu:
    image: ubuntu-ssh-4
    command: /usr/sbin/sshd -D
    networks:
      - testnet
networks:
  testnet:
